import roomCardImg from '@/assets/images/roomCard.png'

export const mockProperties = [
  {
    id: 1,
    image: roomCardImg,
    title: 'Warm and Cozy Apartment',
    location: 'Belia Gargen, California',
    beds: 1,
    baths: 1,
    sqft: 990,
    price: 4321,
    status: 'For Sale',
    type: 'apartment',
    amenities: ['dishwasher', 'internet'],
    category: 'buying',
    rating: 4,
  },
  {
    id: 2,
    image: roomCardImg,
    title: 'Modern Family Home',
    location: 'Downtown District',
    beds: 3,
    baths: 2,
    sqft: 1600,
    price: 18500,
    status: 'For Sale',
    type: 'house',
    amenities: ['dishwasher', 'floor-coverings', 'supermarket'],
    category: 'buying',
    rating: 5,
  },
  {
    id: 3,
    image: roomCardImg,
    title: 'City Studio',
    location: 'City Center',
    beds: 1,
    baths: 1,
    sqft: 520,
    price: 6500,
    status: 'For Rent',
    type: 'studio',
    amenities: ['internet', 'kids-zone'],
    category: 'renting',
    rating: 3,
  },
  {
    id: 4,
    image: roomCardImg,
    title: 'Single Family Retreat',
    location: 'Green Valley',
    beds: 4,
    baths: 3,
    sqft: 2400,
    price: 52000,
    status: 'For Sale',
    type: 'single-family',
    amenities: ['dishwasher', 'built-wardrobes'],
    category: 'buying',
    rating: 4,
  },
  {
    id: 5,
    image: roomCardImg,
    title: 'Sunset Apartment',
    location: 'Beverly Hills',
    beds: 2,
    baths: 2,
    sqft: 1200,
    price: 9800,
    status: 'For Rent',
    type: 'apartment',
    amenities: ['dishwasher', 'floor-coverings', 'internet'],
    category: 'renting',
    rating: 5,
  },
  {
    id: 6,
    image: roomCardImg,
    title: 'Premium Villa',
    location: 'Palm Springs',
    beds: 5,
    baths: 4,
    sqft: 3100,
    price: 76000,
    status: 'For Sale',
    type: 'house',
    amenities: ['dishwasher', 'floor-coverings', 'internet', 'supermarket', 'kids-zone'],
    category: 'buying',
    rating: 5,
  },
  {
    id: 7,
    image: roomCardImg,
    title: 'Comfort Living Townhome',
    location: 'West Side',
    beds: 3,
    baths: 2,
    sqft: 1900,
    price: 11000,
    status: 'For Rent',
    type: 'house',
    amenities: ['internet', 'supermarket'],
    category: 'renting',
    rating: 4,
  },
  {
    id: 8,
    image: roomCardImg,
    title: 'Smart Living Flat',
    location: 'Midtown',
    beds: 1,
    baths: 1,
    sqft: 880,
    price: 7800,
    status: 'For Sale',
    type: 'apartment',
    amenities: ['dishwasher', 'supermarket'],
    category: 'buying',
    rating: 4,
  },
  {
    id: 9,
    image: roomCardImg,
    title: 'Garden House',
    location: 'Suburbs',
    beds: 2,
    baths: 2,
    sqft: 1350,
    price: 9200,
    status: 'For Sale',
    type: 'house',
    amenities: ['dishwasher', 'internet', 'built-wardrobes'],
    category: 'buying',
    rating: 3,
  },
  {
    id: 10,
    image: roomCardImg,
    title: 'Minimal Studio',
    location: 'Old Town',
    beds: 1,
    baths: 1,
    sqft: 600,
    price: 5200,
    status: 'For Rent',
    type: 'studio',
    amenities: ['internet'],
    category: 'renting',
    rating: 2,
  },
  {
    id: 11,
    image: roomCardImg,
    title: 'Single Family Haven',
    location: 'Hillside',
    beds: 5,
    baths: 3,
    sqft: 2100,
    price: 49000,
    status: 'For Sale',
    type: 'single-family',
    amenities: ['floor-coverings', 'supermarket', 'built-wardrobes'],
    category: 'buying',
    rating: 4,
  },
  {
    id: 12,
    image: roomCardImg,
    title: 'Downtown Apartment',
    location: 'Business Bay',
    beds: 2,
    baths: 1,
    sqft: 1050,
    price: 15000,
    status: 'For Rent',
    type: 'apartment',
    amenities: ['dishwasher', 'internet', 'kids-zone'],
    category: 'renting',
    rating: 4,
  },
]
