import apartmentCardImage from '@/assets/images/apartmentCard.png'
import agent1Image from '@/assets/images/agent1.png'
import agent2Image from '@/assets/images/agent2.png'
import agent3Image from '@/assets/images/agent3.png'
import agent4Image from '@/assets/images/agent4.png'
import agentDetailsImage from '@/assets/images/agentDetails.png'
import roomCardImage from '@/assets/images/roomCard.png'
import ourPortfolio1 from '@/assets/images/ourPortfolio1.png'
import ourPortfolio2 from '@/assets/images/ourPortfolio2.png'
import ourPortfolio3 from '@/assets/images/ourPortfolio3.png'
import ourPortfolio4 from '@/assets/images/ourPortfolio4.png'
import ourPortfolio5 from '@/assets/images/ourPortfolio5.png'
import ourPortfolio6 from '@/assets/images/ourPortfolio6.png'
import portfolioList1 from '@/assets/images/portfolioList1.png'
import detailGallery1 from '@/assets/PropertyDetails/gallery1.png'
import detailGallery2 from '@/assets/PropertyDetails/gallery2.png'
import detailGallery3 from '@/assets/PropertyDetails/gallery3.png'
import detailGallery4 from '@/assets/PropertyDetails/gallery4.png'
import detailGallery5 from '@/assets/PropertyDetails/gallery5.png'
import detailMapImage from '@/assets/PropertyDetails/map.png'
import propertyPortfolio1 from '@/assets/PropertyDetails/PortfolioList1.png'
import propertyPortfolio2 from '@/assets/PropertyDetails/PortfolioList2.png'
import propertyPortfolio3 from '@/assets/PropertyDetails/PortfolioList3.png'
import reviewProfile1Image from '@/assets/PropertyDetails/reviewProfile1.png'
import reviewProfile2Image from '@/assets/PropertyDetails/reviewProfile2.png'
import portfolioDetailsMainImage from '@/assets/PortfolioDetailsPage/main.png'
import portfolioDetailsImage1 from '@/assets/PortfolioDetailsPage/Image1.png'
import portfolioDetailsImage2 from '@/assets/PortfolioDetailsPage/Image2.png'
import portfolioDetailsImage3 from '@/assets/PortfolioDetailsPage/Image3.png'

const SAMPLE_VIDEO_URL =
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'

const propertyImages = [
  roomCardImage,
  apartmentCardImage,
  detailGallery2,
  propertyPortfolio1,
  propertyPortfolio3,
  detailGallery1,
  detailGallery3,
  detailGallery4,
  detailGallery5,
  ourPortfolio2,
  ourPortfolio5,
  ourPortfolio6,
]

const propertyGalleries = [
  [
    { image: detailGallery1, alt: 'Bright living room with arched windows and fireplace' },
    { image: detailGallery2, alt: 'Open-plan lounge with patio access and natural light' },
    { image: detailGallery3, alt: 'Bedroom corner with wooden console and mirror' },
    { image: detailGallery4, alt: 'Soft neutral sitting room with layered textures' },
    { image: detailGallery5, alt: 'Minimal interior with wooden cabinet and armchair' },
  ],
  [
    { image: detailGallery2, alt: 'Open living room with full-height windows' },
    { image: detailGallery1, alt: 'Modern residential interior with warm flooring' },
    { image: detailGallery4, alt: 'Neutral-toned sitting room with soft daylight' },
    { image: detailGallery5, alt: 'Contemporary corner styling with wood finishes' },
    { image: detailGallery3, alt: 'Bedroom with a practical and elegant layout' },
  ],
  [
    { image: detailGallery3, alt: 'Compact bedroom with modern finishing details' },
    { image: detailGallery2, alt: 'Studio lounge with open circulation' },
    { image: detailGallery5, alt: 'Minimal furniture composition with warm textures' },
    { image: detailGallery4, alt: 'Quiet seating area with layered neutral fabrics' },
    { image: detailGallery1, alt: 'Living space with fireplace and natural light' },
  ],
]

const portfolioDetailSets = [
  {
    mainImage: portfolioDetailsMainImage,
    gallery: [
      {
        image: portfolioDetailsImage1,
        alt: 'Bright living room with fireplace and warm wood floors',
      },
      {
        image: portfolioDetailsImage2,
        alt: 'Soft neutral lounge with layered textiles and coffee table',
      },
      {
        image: portfolioDetailsImage3,
        alt: 'Styled sitting area with orange accent chair and indoor plants',
      },
    ],
  },
  {
    mainImage: ourPortfolio1,
    gallery: [
      { image: detailGallery1, alt: 'Warm residential interior with full-height windows' },
      { image: detailGallery2, alt: 'Open-plan family lounge with soft lighting' },
      { image: detailGallery4, alt: 'Refined living area with a neutral design palette' },
    ],
  },
  {
    mainImage: ourPortfolio6,
    gallery: [
      { image: propertyPortfolio1, alt: 'Modern villa photographed during evening light' },
      { image: propertyPortfolio2, alt: 'Angular facade and landscaped front yard' },
      { image: propertyPortfolio3, alt: 'Residential exterior with clean geometric lines' },
    ],
  },
]

export const fakeDb = {
  siteSettings: {
    homeHeroStats: [
      { id: 'premium-products', value: '1500' },
      { id: 'happy-customers', value: '324k' },
      { id: 'award-winning', value: '1200' },
    ],
    socialLinks: {
      facebook: 'https://facebook.com/afaqalomran.dev',
      instagram: 'https://instagram.com/afaqalomran.dev',
      whatsapp: 'https://wa.me/963937302533',
    },
    contact: {
      primaryEmail: 'homeq.example@gmail.com',
      primaryPhone: '+963 937 302 533',
      footerPhoneLabel: '(208) 555-0112',
      footerPhoneHref: 'tel:+12085550112',
      footerEmailLabel: 'homeq.example@gmail.com',
      footerEmailHref: 'mailto:homeq.example@gmail.com',
      contactAddress: 'Damascus, Syria',
      footerAddress: 'Damascus, Syria',
    },
    mapEmbedUrl:
      'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d18429.444688130417!2d36.2766021818303!3d33.50641459414196!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x1518e1005eaa110f%3A0xf57a927322ed1e08!2zRGlnaXQt2K_Zitis2Ko!5e0!3m2!1sar!2sus!4v1773839074688!5m2!1sar!2sus',
    homeTestimonialVideoUrl: SAMPLE_VIDEO_URL,
  },
  phoneCountries: [
    { code: 'SY', dialCode: '+963', flag: '🇸🇾', nameEn: 'Syria', nameAr: 'سوريا' },
    { code: 'IQ', dialCode: '+964', flag: '🇮🇶', nameEn: 'Iraq', nameAr: 'العراق' },
    { code: 'SA', dialCode: '+966', flag: '🇸🇦', nameEn: 'Saudi Arabia', nameAr: 'السعودية' },
    {
      code: 'AE',
      dialCode: '+971',
      flag: '🇦🇪',
      nameEn: 'United Arab Emirates',
      nameAr: 'الإمارات',
    },
    { code: 'JO', dialCode: '+962', flag: '🇯🇴', nameEn: 'Jordan', nameAr: 'الأردن' },
    { code: 'LB', dialCode: '+961', flag: '🇱🇧', nameEn: 'Lebanon', nameAr: 'لبنان' },
    { code: 'EG', dialCode: '+20', flag: '🇪🇬', nameEn: 'Egypt', nameAr: 'مصر' },
    { code: 'TR', dialCode: '+90', flag: '🇹🇷', nameEn: 'Turkey', nameAr: 'تركيا' },
    { code: 'QA', dialCode: '+974', flag: '🇶🇦', nameEn: 'Qatar', nameAr: 'قطر' },
    { code: 'KW', dialCode: '+965', flag: '🇰🇼', nameEn: 'Kuwait', nameAr: 'الكويت' },
    { code: 'US', dialCode: '+1', flag: '🇺🇸', nameEn: 'United States', nameAr: 'الولايات المتحدة' },
    {
      code: 'GB',
      dialCode: '+44',
      flag: '🇬🇧',
      nameEn: 'United Kingdom',
      nameAr: 'المملكة المتحدة',
    },
    { code: 'DE', dialCode: '+49', flag: '🇩🇪', nameEn: 'Germany', nameAr: 'ألمانيا' },
    { code: 'FR', dialCode: '+33', flag: '🇫🇷', nameEn: 'France', nameAr: 'فرنسا' },
  ],
  properties: [
    {
      id: 1,
      image: propertyImages[0],
      title: 'One-Bedroom Apartment in Dummar',
      location: 'Dummar Project, Damascus',
      beds: 1,
      baths: 1,
      sqft: 990,
      price: 28000,
      status: 'For Sale',
      type: 'apartment',
      amenities: ['dishwasher', 'internet'],
      category: 'buying',
      rating: 4,
      numberOfUnits: 18,
      gallery: propertyGalleries[0],
      mapImage: detailMapImage,
      videoUrl: SAMPLE_VIDEO_URL,
      contactAgentId: 'esther-howard',
      portfolioIds: ['front-view-residence', 'minimal-white-facade', 'contemporary-timber-facade'],
      relatedPropertyIds: [2, 3, 4, 5],
      reviewImages: [reviewProfile1Image, reviewProfile2Image],
    },
    {
      id: 2,
      image: propertyImages[1],
      title: 'Family House in Al-Malki',
      location: 'Al-Malki, Damascus',
      beds: 3,
      baths: 2,
      sqft: 1600,
      price: 95000,
      status: 'For Sale',
      type: 'house',
      amenities: ['dishwasher', 'floor-coverings', 'supermarket'],
      category: 'buying',
      rating: 5,
      numberOfUnits: 24,
      gallery: propertyGalleries[1],
      mapImage: detailMapImage,
      videoUrl: SAMPLE_VIDEO_URL,
      contactAgentId: 'cameron-williamson',
      portfolioIds: ['sunlit-bedroom-suite', 'luxury-kitchen-interior', 'modern-villa-at-dusk'],
      relatedPropertyIds: [1, 4, 6, 7],
      reviewImages: [reviewProfile2Image, reviewProfile1Image],
    },
    {
      id: 3,
      image: propertyImages[2],
      title: 'Furnished Studio in Al-Mazzeh',
      location: 'Al-Mazzeh, Damascus',
      beds: 1,
      baths: 1,
      sqft: 520,
      price: 180,
      status: 'For Rent',
      type: 'studio',
      amenities: ['internet', 'kids-zone'],
      category: 'renting',
      rating: 3,
      numberOfUnits: 12,
      gallery: propertyGalleries[2],
      mapImage: detailMapImage,
      videoUrl: SAMPLE_VIDEO_URL,
      contactAgentId: 'brooklyn-simmons',
      portfolioIds: ['courtyard-home-at-dusk', 'open-plan-living-room', 'modern-villa-at-dusk-02'],
      relatedPropertyIds: [1, 5, 8, 10],
      reviewImages: [reviewProfile1Image, reviewProfile2Image],
    },
    {
      id: 4,
      image: propertyImages[3],
      title: 'Independent Villa in Yaafour',
      location: 'Yaafour, Rural Damascus',
      beds: 4,
      baths: 3,
      sqft: 2400,
      price: 145000,
      status: 'For Sale',
      type: 'single-family',
      amenities: ['dishwasher', 'built-wardrobes'],
      category: 'buying',
      rating: 4,
      numberOfUnits: 10,
      gallery: propertyGalleries[0],
      mapImage: detailMapImage,
      videoUrl: SAMPLE_VIDEO_URL,
      contactAgentId: 'robert-fox',
      portfolioIds: ['front-view-residence-02', 'timber-facade-home-02', 'timber-facade-home-03'],
      relatedPropertyIds: [2, 6, 9, 11],
      reviewImages: [reviewProfile2Image, reviewProfile1Image],
    },
    {
      id: 5,
      image: propertyImages[4],
      title: 'Two-Bedroom Apartment in Kafar Souseh',
      location: 'Kafar Souseh, Damascus',
      beds: 2,
      baths: 2,
      sqft: 1200,
      price: 350,
      status: 'For Rent',
      type: 'apartment',
      amenities: ['dishwasher', 'floor-coverings', 'internet'],
      category: 'renting',
      rating: 5,
      numberOfUnits: 30,
      gallery: propertyGalleries[1],
      mapImage: detailMapImage,
      videoUrl: SAMPLE_VIDEO_URL,
      contactAgentId: 'esther-howard',
      portfolioIds: [
        'front-view-residence',
        'luxury-kitchen-interior-02',
        'minimal-white-facade-02',
      ],
      relatedPropertyIds: [1, 3, 6, 12],
      reviewImages: [reviewProfile1Image, reviewProfile2Image],
    },
    {
      id: 6,
      image: propertyImages[5],
      title: 'Luxury Villa in Yaafour',
      location: 'Yaafour, Rural Damascus',
      beds: 5,
      baths: 4,
      sqft: 3100,
      price: 210000,
      status: 'For Sale',
      type: 'house',
      amenities: ['dishwasher', 'floor-coverings', 'internet', 'supermarket', 'kids-zone'],
      category: 'buying',
      rating: 5,
      numberOfUnits: 8,
      gallery: propertyGalleries[2],
      mapImage: detailMapImage,
      videoUrl: SAMPLE_VIDEO_URL,
      contactAgentId: 'cameron-williamson',
      portfolioIds: ['modern-villa-at-dusk', 'courtyard-home-at-dusk-02', 'open-plan-living-room'],
      relatedPropertyIds: [2, 4, 5, 11],
      reviewImages: [reviewProfile2Image, reviewProfile1Image],
    },
    {
      id: 7,
      image: propertyImages[6],
      title: 'Townhouse in Jaramana',
      location: 'Jaramana, Rural Damascus',
      beds: 3,
      baths: 2,
      sqft: 1900,
      price: 420,
      status: 'For Rent',
      type: 'house',
      amenities: ['internet', 'supermarket'],
      category: 'renting',
      rating: 4,
      numberOfUnits: 16,
      gallery: propertyGalleries[0],
      mapImage: detailMapImage,
      videoUrl: SAMPLE_VIDEO_URL,
      contactAgentId: 'brooklyn-simmons',
      portfolioIds: ['front-view-residence', 'sunlit-bedroom-suite', 'luxury-kitchen-interior'],
      relatedPropertyIds: [2, 6, 8, 9],
      reviewImages: [reviewProfile1Image, reviewProfile2Image],
    },
    {
      id: 8,
      image: propertyImages[7],
      title: 'Apartment in Qudsaya Suburb',
      location: 'Qudsaya Suburb, Rural Damascus',
      beds: 1,
      baths: 1,
      sqft: 880,
      price: 38000,
      status: 'For Sale',
      type: 'apartment',
      amenities: ['dishwasher', 'supermarket'],
      category: 'buying',
      rating: 4,
      numberOfUnits: 20,
      gallery: propertyGalleries[1],
      mapImage: detailMapImage,
      videoUrl: SAMPLE_VIDEO_URL,
      contactAgentId: 'robert-fox',
      portfolioIds: ['minimal-white-facade', 'courtyard-home-at-dusk', 'open-plan-living-room'],
      relatedPropertyIds: [3, 5, 7, 10],
      reviewImages: [reviewProfile2Image, reviewProfile1Image],
    },
    {
      id: 9,
      image: propertyImages[8],
      title: 'Garden House in Sahnaya',
      location: 'Sahnaya, Rural Damascus',
      beds: 2,
      baths: 2,
      sqft: 1350,
      price: 62000,
      status: 'For Sale',
      type: 'house',
      amenities: ['dishwasher', 'internet', 'built-wardrobes'],
      category: 'buying',
      rating: 3,
      numberOfUnits: 14,
      gallery: propertyGalleries[2],
      mapImage: detailMapImage,
      videoUrl: SAMPLE_VIDEO_URL,
      contactAgentId: 'esther-howard',
      portfolioIds: ['modern-villa-at-dusk', 'front-view-residence-02', 'timber-facade-home-02'],
      relatedPropertyIds: [4, 7, 8, 11],
      reviewImages: [reviewProfile1Image, reviewProfile2Image],
    },
    {
      id: 10,
      image: propertyImages[9],
      title: 'Compact Studio in Al-Shaalan',
      location: 'Al-Shaalan, Damascus',
      beds: 1,
      baths: 1,
      sqft: 600,
      price: 160,
      status: 'For Rent',
      type: 'studio',
      amenities: ['internet'],
      category: 'renting',
      rating: 2,
      numberOfUnits: 22,
      gallery: propertyGalleries[0],
      mapImage: detailMapImage,
      videoUrl: SAMPLE_VIDEO_URL,
      contactAgentId: 'cameron-williamson',
      portfolioIds: ['timber-facade-home-03', 'modern-villa-at-dusk-02', 'minimal-white-facade-02'],
      relatedPropertyIds: [3, 8, 11, 12],
      reviewImages: [reviewProfile2Image, reviewProfile1Image],
    },
    {
      id: 11,
      image: propertyImages[10],
      title: 'Family Residence in Al-Mazzeh Villas',
      location: 'Al-Mazzeh Villas, Damascus',
      beds: 5,
      baths: 3,
      sqft: 2100,
      price: 128000,
      status: 'For Sale',
      type: 'single-family',
      amenities: ['floor-coverings', 'supermarket', 'built-wardrobes'],
      category: 'buying',
      rating: 4,
      numberOfUnits: 11,
      gallery: propertyGalleries[1],
      mapImage: detailMapImage,
      videoUrl: SAMPLE_VIDEO_URL,
      contactAgentId: 'brooklyn-simmons',
      portfolioIds: [
        'luxury-kitchen-interior',
        'courtyard-home-at-dusk-02',
        'open-plan-living-room',
      ],
      relatedPropertyIds: [4, 6, 9, 10],
      reviewImages: [reviewProfile1Image, reviewProfile2Image],
    },
    {
      id: 12,
      image: propertyImages[11],
      title: 'Apartment for Rent in Al-Waer',
      location: 'Al-Waer, Homs',
      beds: 2,
      baths: 1,
      sqft: 1050,
      price: 300,
      status: 'For Rent',
      type: 'apartment',
      amenities: ['dishwasher', 'internet', 'kids-zone'],
      category: 'renting',
      rating: 4,
      numberOfUnits: 26,
      gallery: propertyGalleries[2],
      mapImage: detailMapImage,
      videoUrl: SAMPLE_VIDEO_URL,
      contactAgentId: 'robert-fox',
      portfolioIds: ['front-view-residence', 'luxury-kitchen-interior-02', 'minimal-white-facade'],
      relatedPropertyIds: [5, 8, 10, 11],
      reviewImages: [reviewProfile2Image, reviewProfile1Image],
    },
  ],
  homeCollections: {
    latestPropertyIds: [1, 2, 3, 4],
    popularPropertyIds: [5, 6, 7, 8],
    reviewItems: [
      { id: 1, image: agent1Image, rating: 4 },
      { id: 2, image: agent2Image, rating: 5 },
      { id: 3, image: agent3Image, rating: 5 },
      { id: 4, image: agent4Image, rating: 4 },
    ],
  },
  agents: [
    {
      id: 'esther-howard',
      image: agent1Image,
      detailImage: agentDetailsImage,
      email: 'esther.howard@example.com',
      phone: '+11234567890',
      socials: {
        facebook: 'https://facebook.com/esther.howard.fake',
        instagram: 'https://instagram.com/esther.howard.fake',
        whatsapp: 'https://wa.me/11234567890',
      },
    },
    {
      id: 'cameron-williamson',
      image: agent2Image,
      detailImage: agentDetailsImage,
      email: 'cameron@example.com',
      phone: '+971555018222',
      socials: {
        facebook: 'https://facebook.com/cameron.w.fake',
        instagram: 'https://instagram.com/cameron.w.fake',
        whatsapp: 'https://wa.me/971555018222',
      },
    },
    {
      id: 'brooklyn-simmons',
      image: agent3Image,
      detailImage: agentDetailsImage,
      email: 'brooklyn@example.com',
      phone: '+447700900333',
      socials: {
        facebook: 'https://facebook.com/brooklyn.s.fake',
        instagram: 'https://instagram.com/brooklyn.s.fake',
        whatsapp: 'https://wa.me/447700900333',
      },
    },
    {
      id: 'robert-fox',
      image: agent4Image,
      detailImage: agentDetailsImage,
      email: 'robert@example.com',
      phone: '+966501234567',
      socials: {
        facebook: 'https://facebook.com/robert.fox.fake',
        instagram: 'https://instagram.com/robert.fox.fake',
        whatsapp: 'https://wa.me/966501234567',
      },
    },
  ],
  portfolios: [
    {
      id: 'front-view-residence',
      image: ourPortfolio1,
      alt: 'Front view of a modern residential house',
      ...portfolioDetailSets[0],
    },
    {
      id: 'minimal-white-facade',
      image: ourPortfolio2,
      alt: 'Minimal white facade residential project',
      ...portfolioDetailSets[1],
    },
    {
      id: 'contemporary-timber-facade',
      image: ourPortfolio3,
      alt: 'Contemporary house with wood and metal facade',
      ...portfolioDetailSets[2],
    },
    {
      id: 'sunlit-bedroom-suite',
      image: ourPortfolio4,
      alt: 'Bedroom interior with modern architecture details',
      ...portfolioDetailSets[0],
    },
    {
      id: 'luxury-kitchen-interior',
      image: ourPortfolio5,
      alt: 'Luxury kitchen interior with warm wood finishes',
      ...portfolioDetailSets[1],
    },
    {
      id: 'modern-villa-at-dusk',
      image: ourPortfolio6,
      alt: 'Evening exterior shot of a modern villa',
      ...portfolioDetailSets[2],
    },
    {
      id: 'courtyard-home-at-dusk',
      image: portfolioList1,
      alt: 'Contemporary courtyard home photographed at dusk',
      ...portfolioDetailSets[0],
    },
    {
      id: 'open-plan-living-room',
      image: detailGallery2,
      alt: 'Open-plan living room with large glass doors',
      ...portfolioDetailSets[1],
    },
    {
      id: 'front-view-residence-02',
      image: ourPortfolio1,
      alt: 'Front view of a modern residential house from another perspective',
      ...portfolioDetailSets[2],
    },
    {
      id: 'timber-facade-home-02',
      image: ourPortfolio3,
      alt: 'Contemporary timber facade home with layered landscaping',
      ...portfolioDetailSets[0],
    },
    {
      id: 'timber-facade-home-03',
      image: ourPortfolio3,
      alt: 'Contemporary timber facade home with elevated entry details',
      ...portfolioDetailSets[1],
    },
    {
      id: 'modern-villa-at-dusk-02',
      image: ourPortfolio6,
      alt: 'Evening exterior shot of a modern villa from another angle',
      ...portfolioDetailSets[2],
    },
    {
      id: 'minimal-white-facade-02',
      image: ourPortfolio2,
      alt: 'Minimal white facade residential project with softened shadowing',
      ...portfolioDetailSets[0],
    },
    {
      id: 'courtyard-home-at-dusk-02',
      image: portfolioList1,
      alt: 'Contemporary courtyard home photographed at dusk in a second portfolio',
      ...portfolioDetailSets[1],
    },
    {
      id: 'luxury-kitchen-interior-02',
      image: ourPortfolio5,
      alt: 'Luxury kitchen interior with warm wood finishes in a second portfolio',
      ...portfolioDetailSets[2],
    },
  ],
  accountProfile: {
    fullName: 'Jone Doe',
    mobile: '+9639425614287',
    email: 'Jonedoe@email.com',
    dateOfBirth: '1999-06-11',
    country: 'Syria',
    houseNumber: '18B',
    streetAddress: 'Al Malki Street',
    floor: '4',
    place: 'Damascus',
    postcode: '10011',
  },
  appointments: [
    { id: 1, propertyId: 1, dateLabel: 'Saturday, 14 Oct 2024', timeLabel: '4:30 PM' },
    { id: 2, propertyId: 4, dateLabel: 'Monday, 21 Oct 2024', timeLabel: '11:00 AM' },
    { id: 3, propertyId: 6, dateLabel: 'Thursday, 24 Oct 2024', timeLabel: '1:15 PM' },
  ],
  favoritePropertyIds: [1, 3, 5, 6, 8, 9, 11, 12],
  notifications: [
    {
      id: 1,
      category: 'agent',
      sender: 'Firas AL-Ahmad',
      senderKey: 'firas',
      unread: true,
      avatarType: 'image',
      avatarSrc: agent1Image,
    },
    {
      id: 2,
      category: 'agent',
      sender: 'Firas AL-Ahmad',
      senderKey: 'firas',
      unread: true,
      avatarType: 'image',
      avatarSrc: agent1Image,
    },
    {
      id: 3,
      category: 'company',
      sender: 'AFAQ',
      senderKey: 'afaq',
      unread: true,
      avatarType: 'company',
    },
    {
      id: 4,
      category: 'company',
      sender: 'AFAQ',
      senderKey: 'afaq',
      unread: true,
      avatarType: 'company',
    },
    {
      id: 5,
      category: 'agent',
      sender: 'Cameron Williamson',
      senderKey: 'cameron',
      unread: false,
      avatarType: 'image',
      avatarSrc: agent2Image,
    },
  ],
  activityLog: {
    authRequests: [],
    inquiries: [],
    reviews: [],
    newsletterSubscriptions: [],
  },
}
